fix bugs

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,7 +42,7 @@ jobs:
           while ! curl -s --head http://localhost:8080 | head -n 1 | grep -q "200 OK"; do echo; sleep 5; done;
           for i in {1..10}; do
             if curl -s --head http://localhost:8080 | head -n 1 | grep -q "200 OK"; then
-              echo "Server is up!"
+              echo "✅ Server is up!"
               break
             else
               echo "Waiting for server... ($i/10)"
@@ -51,20 +51,18 @@ jobs:
           done
 
           if ! curl -s --head http://localhost:8080 | head -n 1 | grep -q "200 OK"; then
-            echo "Server is not up!"
+            echo "❌ Server is not up!"
             exit 1
           fi
 
-      - name: Test create user in TN
+      - name: Create additional user is created in TN
         run: |
-          make create-user
-          make create-user && echo "✅ User created successfully" || { echo "❌ User creation failed"; exit 1; }
+          # Create extra users for restore test later
+          curl 'http://localhost:8080/parse/users' -H 'content-type: text/json' --data-raw '{"username":"ABC$(TN_USER)","password":"ABC$(TN_USER)","email":"ABC$(TN_USER)","timeZone":"America/New_York","_ApplicationId":"123456","_ClientVersion":"js5.3.0"}'
+          [ $? -eq 0 ] && echo "✅ User created successfully" || { echo "❌ User creation failed"; exit 1; }
 
       - name: Test backup
         run: |
-          # Create extra users for restore test later
-          curl 'http://localhost:8080/parse/users' -H 'content-type: text/json' --data-raw '{"username":"$(TN_USER)123","password":"$(TN_USER)123","email":"$(TN_USER)123","timeZone":"America/New_York","_ApplicationId":"123456","_ClientVersion":"js5.3.0"}'
-
           ( make backup ) 2>/dev/null
 
           # Wait for the server to start after backup
@@ -83,7 +81,7 @@ jobs:
           done
 
           if ! curl -s --head http://localhost:8080 | head -n 1 | grep -q "200 OK"; then
-            echo "Server is not up! ❌ Backup failed"
+            echo "❌ Backup failed; Server is not up!"
             exit 1
           else
             echo "✅ Backup successful"
@@ -108,7 +106,7 @@ jobs:
             fi
           done
 
-          ( make restore 2>/dev/null) &
+          ( make restore 2>/dev/null ) &
           # Wait for the server to start after restore
           echo "Waiting for TradeNote server to start..."
           
@@ -124,8 +122,8 @@ jobs:
             fi
           done
 
-          curl 'http://localhost:8080/parse/users' -H 'content-type: text/json' --data-raw '{"username":"$(TN_USER)123","password":"$(TN_USER)123","email":"$(TN_USER)123","timeZone":"America/New_York","_ApplicationId":"123456","_ClientVersion":"js5.3.0"}'
-          echo $? && echo "✅ Restore successful" || { echo "❌ Restore failed"; exit 1; }
+          curl 'http://localhost:8080/parse/users' -H 'content-type: text/json' --data-raw '{"username":"ABC$(TN_USER)","password":"ABC$(TN_USER)","email":"ABC$(TN_USER)","timeZone":"America/New_York","_ApplicationId":"123456","_ClientVersion":"js5.3.0"}'
+          [ $? -ne 0 ] && echo "✅ User exists after restore" || { echo "❌ User does not exist after restore"; exit 1; }
 
       - name: Test update src deps
         run: |
